#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
  if command -v systemctl >/dev/null 2>&1; then
    systemctl stop photoframe.service >/dev/null || true
    systemctl disable photoframe.service >/dev/null || true
    systemctl daemon-reload || true
  fi
fi

exit 0

